### ISSUE TITLE
Scanning a Tempfile which exists in memory

### ISSUE THREAD

**Issue by aidandamerell** [kobaltz/clamby#26]
It would be handy if you could scan a Tempfile (child of File) object as it exists in memory.
`irb> require 'tempfile'`
`file = Tempfile.open("/path/to/file/file.txt")`
`file.unlink`
`Clamby.safe?(file)`

I realise this may be a limitation as clamscan but thought I would make the suggestion anyway.

**Comment by janko-m** [comment]
It appears that `clamscan` supports taking data from standard input, so with Open3 this should work:

```rb
require "open3"

Open3.popen3("clamscan -") do |stdin, stdout, stderr, thread|
  IO.copy_stream(file, stdin)
  stdin.close

  [stdout.read, stderr.read, thread.value]
end
```

**Comment by aidandamerell** [comment]
After a bit of digging around into clamscan, it appears that there is no way to force it to solely read a file from memory. If passing input from STDIN, clamscan will write the input to a temporary file then scan that. The use-case for this request was to avoid files touching disk so it may be a little redundant.
