### ISSUE TITLE
System calls do not escape arguments

### ISSUE THREAD

**Issue by jschroeder9000** [kobaltz/clamby#3]
Clamby makes system calls using string interpolation.  This creates an attack vector for arbitrary code execution.  They should be escaped properly.

https://github.com/kobaltz/clamby/blob/7df2f696b1406f1917b4d2259506279fc3c57962/lib/clamby.rb#L28

**Comment by kobaltz** [comment]
Thanks for pointing this out @jschroeder9000. 

I have addressed this issue.

https://github.com/kobaltz/clamby/pull/4
