### ISSUE TITLE
Clamby showing every upload as a virus..

### ISSUE THREAD

**Issue by J77J** [kobaltz/clamby#9]
I am running an attache image server [](https://github.com/choonkeat/attache) inside a container managed by dokku, I have added clamby to attache, and on my development machine (not dokku, just running the apps) it works fine... On my server it does not. It complains that every upload is a virus. I know this is likely a dokku/server problem rather than a clamby problem, but I wondered whether anyone might have an idea of what the problem could be?

clamby configuration:

```
# setup clamby
Clamby.configure({
                  :check => false,
                  :daemonize => true,
                  :error_clamscan_missing => false,
                  :error_file_missing => false,
                  :error_file_virus => true
                })
```

then just after upload:

```
          # check if free from viruses with clamby
          unless Clamby.safe?(path_of(cachekey))
            File.delete(path_of(cachekey))
            # raise virus-found error 
            raise 'Upload infected with a virus - rejected.'
          end
```

the error I get back is:
`VIRUS DETECTED on 2017-09-22 15:22:59 +0000: /tmp/076/6B2/attache.myserver.com%2F7f%2F9c%2Fa8%2F4d%2Ff1%2F80%2Fe1%2F84%2F94%2F2c%2Fd0%2F98%2Fe3%2F35%2F68%2F1d%2Ftest-pic.jpeg `

so am I right in assuming that the file is being scanned and giving a false positive? Or could the real error be masked here? I am thinking it seems like the latter as the file is definitely virus free...

As I say, I know this is unlikely a clamby issue, but I was hoping you might be able to point me in the direction of what the real error might be (as it certainly looks as though clamav is running fine, and the file is found and scanned) - or at least if I might get this error even if the real problem is not that a virus has been found (maybe the file is not being scanned or not found or something)?

Thanks,

J

**Comment by kobaltz** [comment]
WIth it configured as a daemon, can you confirm that the clamav service is running?

**Comment by J77J** [comment]
Well, that could certainly be a problem couldn't it... Yes - its failing to start for some reason. Although I did try with :daemonize => false and it gave the same results unfortunately

**Comment by kobaltz** [comment]
I know with ClamAV, you have to edit the config files to remove the `Example` line in the config. Same for the FreshClam config. Also make sure that you have the definitions downloaded via `sudo freshclam`. It can take a while for those to download.

**Comment by J77J** [comment]
yes - config files seem correct and freshclam is up to date...

I have resolved the clamd problem as well so that is now up and running.

Would it show a virus found error if it didn't have permission to scan or anything like that do you know, or does it really think that file is a virus?

**Comment by kobaltz** [comment]
Problem with interfacing with the clamby cli app initially was that it returned truthy for when there was a virus or the command could not be found. I'll look into it more to see if I can raise a different kind of exception if the ClamAV could not be found (or daemon not started).

**Comment by J77J** [comment]
Thanks, I've changed clam to run as root and still no joy. I'm pretty stumped tbh.

**Comment by J77J** [comment]
Ok - I got a chance to look at this again and after a bit of rooting through code etc I've ascertained that it is as you say and the command couldn't be found inside the container - so not a problem with Clamby at all. Thanks again!
